export HAB_ORIGIN="workshop"
export PRIMARY_DEPOT="https://ip-172-31-54-5.us-west-2.compute.internal/bldr/v1/"
export PRIMARY_BUILDER="https://ip-172-31-54-5.us-west-2.compute.internal/bldr/v1/"
export LOCAL_BUILDER="https://ip-172-31-54-7.us-west-2.compute.internal/bldr/v1/"

export PRIMARY_PAT="_Qk9YLTEKYmxkci0yMDIyMTAyMTAzMjQyMgpibGRyLTIwMjIxMDIxMDMyNDIyClR3cFN0UnRRQTQ4UE85YTg1cEVzZ1NNWVk2aHpYZUs5CmxsbTVQQ0NwOFRBYzRhYlgrWnhQdDc5M01Rc3RCZDhWTUdZZ2VzU1paVisxV0Z6SQ=="
export SECONDARY_PAT="_Qk9YLTEKYmxkci0yMDIyMTAyNjE1NDk1NQpibGRyLTIwMjIxMDI2MTU0OTU1CjFtT0hxQy9xQ3BLYmFNaEdsUmxDTFZJbkpOeVhXampqCndxT3FWa1pIQTFSUmdtdkhQQkdGT1BJM3o1Ymw3VUVqK2ptU0E0bGdPaFBMUFJNZw=="
export GLOBAL_PAT="_Qk9YLTEKYmxkci0yMDE3MDkyNzAyMzcxNApibGRyLTIwMTcwOTI3MDIzNzE0ClJDcXNzcWdOazBWTlptMGJJanQwYklUWDkvc3lkT3BQCmRVSzBWbHRTVzNWY2FiSUFGTUxQSERVMDQ0T2RmUzYrR2h4SlBRVnVCeVBTUGpNag=="
