port=8010
interval=60
run_lock_timeout = 1800
log_level = "warn"
env_path_prefix = "/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
ssl_verify_mode = ":verify_peer"
verify_api_cert = false
rubygems_url = "https://www.rubygems.org"

[chef_license]
acceptance="accept-no-persist"

[automate]
enable=true
server_url="http://127.0.0.1/services/capture/"               
#server_url="https://172.31.54.5"               
token="E2bCL2WgfBqyo_lw8M-2OWm8WT0="
node_uuid="11111111-1111-1111-1111-111111111111"
environment="host"