#!/bin/sh
echo "Setting up Effortless InSpec"

SRC=$(curl -s localhost:9631/census)
DATA=$(echo $SRC | grep -Pio -m1 '"member_id":"[^"]*"' | grep -Eo -m1 '[^:]*$')
echo $DATA

#sed -i "s/\"11111111-1111-1111-1111-111111111111\"/$DATA/" {{pkg.svc_config_path}}/inspec_exec_config.json
#cat {{pkg.svc_config_path}}/inspec_exec_config.json

#return 0
mkdir /hab/user/
mkdir /hab/user/host_compliance
mkdir /hab/user/host_compliance/config
#touch /hab/user/host_compliance/config/user.toml
#echo "[automate]" > /hab/user/host_compliance/config/user.toml
#echo "node_uuid=\"$DATA\"" >> /hab/user/host_compliance/config/user.toml

#cat /hab/user/host_compliance/config/user.toml

echo "Done setting up Effortless InSpec"
