#!/bin/sh

echo "##START## SETTING UP THE POST RUN CONFIG"

SRC=$(curl -s localhost:9631/census)
DATA=$(echo $SRC | grep -Pio -m1 '"member_id":"[^"]*"' | grep -Eo -m1 '[^:]*$')
echo $DATA

#sed -i "s/\"00000000-0000-0000-0000-000000000000\"/$DATA/" {{pkg.svc_config_path}}/inspec_exec_config.json
echo "sed -i \"s/\"11111111-1111-1111-1111-111111111111\"/$DATA/\" {{pkg.svc_config_path}}/inspec_exec_config.json"
#sed -i "s/\"11111111-1111-1111-1111-111111111111\"/$DATA/" {{pkg.svc_config_path}}/inspec_exec_config.json
#cat {{pkg.svc_config_path}}/inspec_exec_config.json

echo "DONE SETTING UP THE POST RUN CONFIG"

#return 0